export const GET_APARTMENT_REQUEST = "GET_APARTMENT_REQUEST";
export const GET_APARTMENT_SUCCESS = "GET_APARTMENT_SUCCESS";
export const GET_APARTMENT_FAIL = "GET_APARTMENT_FAIL";

export const APARTMENT_DETAIL_REQUEST = "APARTMENT_DETAIL_REQUEST";
export const APARTMENT_DETAIL_SUCCESS = "APARTMENT_DETAIL_SUCCESS";
export const APARTMENT_DETAIL_FAIL = "APARTMENT_DETAIL_FAIL";

export const SEARCH_APARTMENT_REQUEST = "SEARCH_APARTMENT_REQUEST";
export const SEARCH_APARTMENT_SUCCESS = "SEARCH_APARTMENT_SUCCESS";
export const SEARCH_APARTMENT_FAIL = "SEARCH_APARTMENT_FAIL";
export const SEARCH_APARTMENT_RESET = "SEARCH_APARTMENT_RESET";
