export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";
export const CREATE_BOOKING_RESET = "CREATE_BOOKING_RESET";

export const GET_HISTORY_BOOKING_REQUEST = "GET_HISTORY_BOOKING_REQUEST";
export const GET_HISTORY_BOOKING_SUCCESS = "GET_HISTORY_BOOKING_SUCCESS";
export const GET_HISTORY_BOOKING_FAIL = "GET_HISTORY_BOOKING_FAIL";

export const GET_OWNER_BOOKING_REQUEST = "GET_OWNER_BOOKING_REQUEST";
export const GET_OWNER_BOOKING_SUCCESS = "GET_OWNER_BOOKING_SUCCESS";
export const GET_OWNER_BOOKING_FAIL = "GET_OWNER_BOOKING_FAIL";

export const GET_OWNER_BOOKING_DETAIL_REQUEST =
  "GET_OWNER_BOOKING_DETAIL_REQUEST";
export const GET_OWNER_BOOKING_DETAIL_SUCCESS =
  "GET_OWNER_BOOKING_DETAIL_SUCCESS";
export const GET_OWNER_BOOKING_DETAIL_FAIL = "GET_OWNER_BOOKING_DETAIL_FAIL";

export const GET_BOOKING_DETAIL_REQUEST = "GET_BOOKING_DETAIL_REQUEST";
export const GET_BOOKING_DETAIL_SUCCESS = "GET_BOOKING_DETAIL_SUCCESS";
export const GET_BOOKING_DETAIL_FAIL = "GET_BOOKING_DETAIL_FAIL";

export const CANCEL_BOOKING_REQUEST = "CANCEL_BOOKING_REQUEST";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
export const CANCEL_BOOKING_FAIL = "CANCEL_BOOKING_FAIL";
export const CANCEL_BOOKING_RESET = "CANCEL_BOOKING_RESET";
