export const DATE_RANGE_BOOKING_REQUEST = "DATE_RANGE_BOOKING_REQUEST";
export const DATE_RANGE_BOOKING_SUCCESS = "DATE_RANGE_BOOKING_SUCCESS";
export const DATE_RANGE_BOOKING_FAIL = "DATE_RANGE_BOOKING_FAIL";

export const DATE_RANGE_DEFAULT_REQUEST = "DATE_RANGE_DEFAULT_REQUEST";
export const DATE_RANGE_DEFAULT_SUCCESS = "DATE_RANGE_DEFAULT_SUCCESS";
export const DATE_RANGE_DEFAULT_FAIL = "DATE_RANGE_DEFAULT_FAIL";

export const DATE_OUT_REQUEST = "DATE_OUT_REQUEST";
export const DATE_OUT_SUCCESS = "DATE_OUT_SUCCESS";
export const DATE_OUT_FAIL = "DATE_OUT_FAIL";
