export const CREATE_OWNERSHIP_REQUEST = "CREATE_OWNERSHIP_REQUEST";
export const CREATE_OWNERSHIP_SUCCESS = "CREATE_OWNERSHIP_SUCCESS";
export const CREATE_OWNERSHIP_FAIL = "CREATE_OWNERSHIP_FAIL";
export const CREATE_OWNERSHIP_RESET = "CREATE_OWNERSHIP_RESET";

export const GET_OWNERSHIP_REQUEST = "GET_OWNERSHIP_REQUEST";
export const GET_OWNERSHIP_SUCCESS = "GET_OWNERSHIP_SUCCESS";
export const GET_OWNERSHIP_FAIL = "GET_OWNERSHIP_FAIL";

export const GET_OWNERSHIP_DETAIL_REQUEST = "GET_OWNERSHIP_DETAIL_REQUEST";
export const GET_OWNERSHIP_DETAIL_SUCCESS = "GET_OWNERSHIP_DETAIL_SUCCESS";
export const GET_OWNERSHIP_DETAIL_FAIL = "GET_OWNERSHIP_DETAIL_FAIL";
