export const GET_LIST_PROPERTY_REQUEST = "GET_LIST_PROPERTY_REQUEST";
export const GET_LIST_PROPERTY_SUCCESS = "GET_LIST_PROPERTY_SUCCESS";
export const GET_LIST_PROPERTY_FAIL = "GET_LIST_PROPERTY_FAIL";
