export const GET_RATINGS_BOOKING_REQUEST = "GET_RATINGS_BOOKING_REQUEST";
export const GET_RATINGS_BOOKING_SUCCESS = "GET_RATINGS_BOOKING_SUCCESS";
export const GET_RATINGS_BOOKING_FAILURE = "GET_RATINGS_BOOKING_FAILURE";

export const GET_RATINGS_APARTMENT_REQUEST = "GET_RATINGS_APARTMENT_REQUEST";
export const GET_RATINGS_APARTMENT_SUCCESS = "GET_RATINGS_APARTMENT_SUCCESS";
export const GET_RATINGS_APARTMENT_FAIL = "GET_RATINGS_APARTMENT_FAIL";

export const CREATE_RATING_BOOKING_REQUEST = "CREATE_RATING_BOOKING_REQUEST";
export const CREATE_RATING_BOOKING_SUCCESS = "CREATE_RATING_BOOKING_SUCCESS";
export const CREATE_RATING_BOOKING_FAIL = "CREATE_RATING_BOOKING_FAIL";
export const CREATE_RATING_BOOKING_RESET = "CREATE_RATING_BOOKING_RESET";
