export const GET_LIST_RESORT_REQUEST = "GET_LIST_RESORT_REQUEST";
export const GET_LIST_RESORT_SUCCESS = "GET_LIST_RESORT_SUCCESS";
export const GET_LIST_RESORT_FAIL = "GET_LIST_RESORT_FAIL";

export const GET_LIST_RESORT_ACTIVE_REQUEST = "GET_LIST_RESORT_ACTIVE_REQUEST";
export const GET_LIST_RESORT_ACTIVE_SUCCESS = "GET_LIST_RESORT_ACTIVE_SUCCESS";
export const GET_LIST_RESORT_ACTIVE_FAIL = "GET_LIST_RESORT_ACTIVE_FAIL";
