export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const SEARCH_ALL_USER_REQUEST = "SEARCH_ALL_USER_REQUEST";
export const SEARCH_ALL_USER_SUCCESS = "SEARCH_ALL_USER_SUCCESS";
export const SEARCH_ALL_USER_FAIL = "SEARCH_ALL_USER_FAIL";

export const SEARCH_USER_BY_EMAIL_REQUEST = "SEARCH_USER_BY_EMAIL_REQUEST";
export const SEARCH_USER_BY_EMAIL_SUCCESS = "SEARCH_USER_BY_EMAIL_SUCCESS";
export const SEARCH_USER_BY_EMAIL_FAIL = "SEARCH_USER_BY_EMAIL_FAIL";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const RESET_PASSWORD_OTP_REQUEST = "RESET_PASSWORD_OTP_REQUEST";
export const RESET_PASSWORD_OTP_SUCCESS = "RESET_PASSWORD_OTP_SUCCESS";
export const RESET_PASSWORD_OTP_FAIL = "RESET_PASSWORD_OTP_FAIL";
export const RESET_PASSWORD_OTP_RESET = "RESET_PASSWORD_OTP_RESET";

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL";
export const CREATE_CONVERSATION_RESET = "CREATE_CONVERSATION_RESET";

export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST";
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS";
export const GET_CONVERSATION_FAIL = "GET_CONVERSATION_FAIL";
