// walletConstants.js

export const GET_TOTAL_POINT_REQUEST = "GET_TOTAL_POINT_REQUEST";
export const GET_TOTAL_POINT_SUCCESS = "GET_TOTAL_POINT_SUCCESS";
export const GET_TOTAL_POINT_FAIL = "GET_TOTAL_POINT_FAIL";

export const GET_TRANSACTION_HISTORY_REQUEST =
  "GET_TRANSACTION_HISTORY_REQUEST";
export const GET_TRANSACTION_HISTORY_SUCCESS =
  "GET_TRANSACTION_HISTORY_SUCCESS";
export const GET_TRANSACTION_HISTORY_FAIL = "GET_TRANSACTION_HISTORY_FAIL";
